apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-httpd-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-httpd-site
  template:
    metadata:
      labels:
        app: my-httpd-site
    spec:
      containers:
      - name: my-httpd-site
        image: 65.0.26.117:8082/my-httpd-site:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: nexus-creds
